# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
